config/routes.rb
Rails.application.routes.draw do

  scope module: :web do
    get 'welcome/index'
    resources :articles, only: [:index, :show, :destroy, :new, :create, :edit, :update] do
      scope module: :articles do
        resources :comments, only: [:create, :destroy]
      end
    end
    namespace :moderation do
      resources :articles, only: [:edit, :update, :create]
    end
  end

  root 'web/welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include AASM

  aasm :column => 'state' do
    state :draft, initial: true
    state :moderation, :published

    event :moderate do
      transitions from: :draft, to: :moderation
    end

    event :publish do
      transitions from: :moderation, to: :published
    end
  end

  validates :title, presence: true, length: { minimum: 5 }

  has_many :comments, dependent: :destroy
  belongs_to :category, required: false
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
end

app/models/article/comment.rb
class Article::Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "viraj", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "viraj", password: "password", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commentor, :body)
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/web/articles/application_controller.rb
class Web::Articles::ApplicationController < Web::ApplicationController

end

app/controllers/web/articles/comments_controller.rb
class Web::Articles::CommentsController < Web::Articles::ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:article_comment).permit(:commentor, :body)
  end
end

app/controllers/web/articles_controller.rb
class Web::ArticlesController < Web::ApplicationController
  def index
    @articles = Article.all.includes(:category)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/web/moderation/application_controller.rb
class Web::Moderation::ApplicationController < Web::ApplicationController

end

app/controllers/web/moderation/articles_controller.rb
class Web::Moderation::ArticlesController < Web::Moderation::ApplicationController
  def create
    @article = Article.find(params[:id])
    if @article && @article.may_moderate?
      @article.moderate!
    else
      puts @article.errors.full_messages
    end
    redirect_to articles_path
  end

  def edit
    @article = Web::ModerationArticleType.find(params[:id])
  end

  def update
    @article = Web::ModerationArticleType.find(params[:id])
    if @article.update_attributes(web_moderation_article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private

    def web_moderation_article_params
      params.fetch(:article, {})
    end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/index.html.erb
<h1>Articles: </h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <%= link_to 'New article', new_article_path %>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
      method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commentor:</strong>
  <%= comment.commentor %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<%= link_to 'Delete comment', [comment.article, comment],
method: :delete,
data: { confirm: 'Are you sure?' } %>
</p>
.........................................

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
  <p>
    <%= form.label :commentor %><br>
    <%= form.text_field :commentor %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/web/article/comments/_comment.html.slim
p
  strong Commentor:
  = comment.commentor
p
  strong Comment:
  = comment.body
p
  = link_to 'Delete comment', article_comment_path(comment.article, comment),
    method: :delete,
    data: { confirm: 'Are you sure?' }
|.........................................

app/views/web/article/comments/_form.html.slim
= simple_form_for @article.comments.build, url: article_comments_path(@article) do |form|
  p
    = form.label :commentor
    br
    = form.text_field :commentor
  p
    = form.label :body
    br
    = form.text_area :body
  p
    = form.submit

app/views/web/articles/_form.html.slim
= simple_form_for @article do |form|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        | prohibited
        | this article from being saved:
      ul
        - @article.errors.full_messages.each do |msg|
          li= msg
  p
    = form.label :title
    br
    = form.text_field :title
  p
    = form.label :text
    br
    = form.text_area :text
  p
    = form.submit

app/views/web/articles/edit.slim
h1 Edit article
= render 'form'
br
  - if @article.may_moderate?
    = button_to 'Send to moderate', moderation_articles_path(id: @article.id)
= link_to 'Back', articles_path

app/views/web/articles/index.html.slim
h1 Articles:
table
  tr
    th Title
    th Text
    th Category
    th State
  = link_to 'New article', new_article_path
  - @articles.each do |article|
    tr
      td= article.title
      td= article.text
      td= article.category&.name
      td= article.state
      td= link_to 'Show', article_path(article)
      td
        - if article.draft?
          = link_to 'Edit', edit_article_path(article)
      td= link_to 'Destroy', article_path(article),
          method: :delete,
          data: { confirm: 'Are you sure?' }
      td
        - if article.may_publish?
          = link_to 'Moderate', edit_moderation_article_path(article)

app/views/web/articles/new.html.slim
h1 New article
= render 'form'
= link_to 'Back', articles_path

app/views/web/articles/show.html.slim
p
  strong Title:
  = @article.title
p
  strong Text:
  = @article.text
p
  strong Category:
  = @article.category&.name
h2 Comments
= render @article.comments
h2 Add a comment:
= render 'web/article/comments/form'
= link_to 'Edit', edit_article_path(@article)
| \
= link_to 'Back', articles_path

app/views/web/moderation/articles/_form.html.slim
= simple_form_for @article do |form|
  p
    = form.label :title
    br
    = form.text_field :title
  p
    = form.label :text
    br
    = form.text_area :text
  p
    = form.collection_select :category_id, Article::Category.all, :id, :name
  p
    = form.submit

app/views/web/moderation/articles/edit.html.slim
h1 Moderate article
= render 'form'
= link_to 'Back', articles_path

app/views/web/welcome/index.html.slim
h1 Blog
= link_to 'My Blog', controller: 'articles'